name: zxplore_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  backdrop: ^0.9.0
  crypto: ^3.0.3
  dio: ^5.3.2
  dio_http2_adapter: ^2.3.1+1
  drift: ^2.11.1
  drift_dev: ^2.11.1
  encrypt: ^5.0.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.10
  flutter_secure_storage: ^9.0.0
  go_router: ^10.1.2
  go_router_builder: ^2.3.1
  image_picker: ^1.0.3
  intl: ^0.18.1
  logging: ^1.2.0
  meta: ^1.9.1
  path: ^1.8.3
  path_provider: ^2.1.0
  retrofit: ^4.0.1
  riverpod_annotation: ^2.1.4
  rxdart: ^0.27.7
  shared_preferences: ^2.2.0
  signature: ^5.4.0
  sqlite3_flutter_libs: ^0.5.16

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  retrofit_generator: ^7.0.8
  riverpod_generator: ^2.3.1

flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - assets/zenithLogo.svg
    - assets/accountType.json
    - assets/server_certificate.crt
    - assets/server_certificate.pem
    - assets/server_certificate_key.pem
