name: zxplore_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  backdrop: ^0.9.0
  crypto: ^3.0.3
  dio: ^5.3.0
  dio_http2_adapter: ^2.3.1
  drift: ^2.10.0
  drift_dev: ^2.10.0
  encrypt: ^5.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_secure_storage: ^8.0.0
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  go_router: ^9.0.3
  go_router_builder: ^2.2.2
  image_picker: ^1.0.1
  intl: ^0.18.0
  logging: ^1.2.0
  meta: ^1.9.1
  path: ^1.8.3
  path_provider: ^2.0.15
  retrofit: ^4.0.1
  retrofit_generator: ^7.0.2
  riverpod_annotation: ^2.1.1
  riverpod_generator: ^2.2.3
  rxdart: ^0.27.7
  shared_preferences: ^2.2.0
  signature: ^5.4.0
  sqlite3_flutter_libs: ^0.5.15

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - assets/zenithLogo.svg
    - assets/accountType.json
    - assets/server_certificate.crt
    - assets/server_certificate.pem
    - assets/server_certificate_key.pem
