
const SAVINGS_ACCOUNT = 'SAVINGS ACCOUNT';
const CURRENT_ACCOUNT = 'CURRENT ACCOUNT';

const DRIVERS_LICENSE = 'DRIVER\'S LICENSE';
const VOTERS_CARD = 'VOTER\'S ID CARD';
const INT_PASSPORT = 'INT\'L PASSPORT';
const SSNIT_CARD = 'SSNIT CARD';
const OTHERS = 'OTHERS';
const NATIONAL_ID = 'NATIONAL ID';
const STUDENT_ID = 'STUDENT ID';
const ASPIRE_ACCOUNT = 'ASPIRE ACCOUNT';

const PLATINUM_ACCOUNT = 'PLATINUM ACCOUNT';
